# Changes here will be overwritten by Copier
_commit: 1.3.2-1-g3cf0a7f
_src_path: /Users/PMI/_code/dana-dtsc-common
default_python_version: '3.10'
docker_image_name: dtsc-common-test
docker_job_name: dtsc_common_test
docker_source: mcr.microsoft.com/azure-functions/python:4-python3.10
docker_version_path: ./src/VERSION
dockerfile_path: ./docker/Dockerfile
is_docker_project: true
is_new_project: false
is_python_package: true
is_python_project: true
newest_numpy_limit: '1.25'
oldest_supported_numpy: 1.21.*
project_description: Common configs & CI templates
project_name: dana-dtsc-common
python_import_name: common_pkg
python_package_name: pmi-dtsc-common-test
python_version_path: ./src/VERSION
use_pmi_packages: false
use_precommit: true

