---
name: common_pkg
channels:
  - conda-forge
dependencies:
  # see deprecation windows:
  # https://scientific-python.org/specs/spec-0000/#support-window
  - python=3.10.*
  - cython
  - pip
  - ipywidgets
  - joblib
  - notebook
  - numpy>=1.23,<1.25
  - openpyxl
  - pandas<2
  - pandera
  - scikit-learn
  - scipy
  - tqdm
  - xlrd
  ## plotting
  - matplotlib
  - seaborn
  ### utilities requirements
  - azure-identity
  - azure-keyvault-secrets
  - python-dateutil
  - pyodbc
  - pyyaml
  - redis-py>=4.5.5
  - snowflake-connector-python
  # - snowflake-snowpark-python # python version incompatibility
  - snowflake-sqlalchemy
  - sqlalchemy
  ### mlflow requirements
  - azure-storage-blob
  - azure-storage-common
  - azure-storage-file-share
  - mlflow==2.3.2
